ElasticSearch adapter for graph and storage
vesoft-inc/nebula-common pull request #260
Opened 2020-10-15 14:25 UTC by bright-starry-sky

2020-10-17 09:34 UTC, bright-starry-sky commented
added create|drop index for meta.

2020-10-19 02:31 UTC, critical27 commented on src/common/plugin/fulltext/FTMetaAdapter.h
> +    virtual bool activeNode(const HttpClient& client,
Is it used for checking liveness?

2020-10-19 02:31 UTC, critical27 commented on src/common/plugin/fulltext/FTUtils.h
> +struct HttpClient {
Could we reuse the `HttpClient` in common?

2020-10-20 01:36 UTC, bright-starry-sky commented on src/common/plugin/fulltext/FTMetaAdapter.h
> +    virtual bool activeNode(const HttpClient& client,
> Is it used for checking liveness?

Yeah, this is the reserved interface for checking valid nodes in the full text cluster

2020-10-20 01:46 UTC, bright-starry-sky commented on src/common/plugin/fulltext/FTUtils.h
> +struct HttpClient {
> Could we reuse the `HttpClient` in common?

Emm, This module will be compiled into a separate dynamic library for plugin. I don't want it to related on too many modules, so it's isolated here. Would you like to compile library thrift into this library as well?

2020-10-26 07:42 UTC, darionyaphet commented on src/common/clients/meta/MetaClient.cpp
> +    if (!loadFulltextClients()) {
Seems Full Text Search is not an optional ?

2020-10-26 07:49 UTC, darionyaphet commented on src/common/plugin/fulltext/elasticsearch/ESGraphAdapter.cpp
> +        LOG(ERROR) << "Http PUT Failed: " << cmd;
Here is `Create Index Failed` ? Not the HTTP transform failed

2020-10-26 09:06 UTC, critical27 commented on src/common/interface/meta.thrift
> +struct SignInFTServiceReq {
Let's discuss the interface of `listener` here. How about `ADD LISTENER ip:port of space space_name`? WDYT?

2020-10-26 11:08 UTC, bright-starry-sky commented on src/common/clients/meta/MetaClient.cpp
> +    if (!loadFulltextClients()) {
> Seems Full Text Search is not an optional ?

yes, the optional in spaceDesc

2020-10-26 11:25 UTC, bright-starry-sky commented on src/common/interface/meta.thrift
> +struct SignInFTServiceReq {
> Let's discuss the interface of `listener` here. How about `ADD LISTENER [LISTENER_TYPE] list<ip:port> of space`? WDYT?
**I was added an option(TEXT_SEARCH=bool) in create space sentence. it saved into `spaceDesc`. What do you think?
for example CREATE SPACE space1(partition_num=9, replica_factor=1, text_search=true );**
> 
> Something like this:
> 
> 1. Add listener
> 2. After `add listener` is called, meta will allocate the listener of different part on those hosts. (need to save these information on meta)
> 3. The process on those hosts will find that it has added new listeners of some parts, then begin to initialize and join the raft group.
> 
> There are two ways to save these information:
> 
> 1. key: listener host, value: space + list<part + type>
> 2. key: space + part + type, value: host
> 
> Which one do you prefer?
**about 2, Is currently active listener host of `value: host`? if yes. I like 2.**

2020-10-26 11:42 UTC, critical27 commented on src/common/interface/meta.thrift
> +struct SignInFTServiceReq {
1. The problem of `CREATE SPACE space1(partition_num=9, replica_factor=1, text_search=true );` is that, it will be hard to tell where is the listener of each partition, because it will be distributed among all active hosts. And it will be harder when we add a new type of listener, the `spaceDesc` need to add more and more field.

2. The both ways to save listener information look ok to me. The first way is easier to load and init, because as for a host, it can simply grab all listener of it. The second way will be more friendly.

2020-10-28 03:11 UTC, darionyaphet commented on src/common/plugin/fulltext/elasticsearch/ESGraphAdapter.cpp
> +    LOG(ERROR) << ret;
why logging ret double?

2020-10-28 03:19 UTC, bright-starry-sky commented on src/common/plugin/fulltext/elasticsearch/ESGraphAdapter.cpp
> +    LOG(ERROR) << ret;
> why logging ret double?

Good point，my fault.

2020-10-31 02:48 UTC, critical27 commented on src/common/plugin/fulltext/FTStorageAdapter.h
> +    virtual StatusOr<bool> bulk(const HttpClient& client,
After digging a little in storage,  there comes one question: since bulk need to support both put and delete in one batch, so I guess the DocItem need one more parameter to know it is put or delete?

The process would be `parse wal` -> `decode into kv with operation type` -> DocItem.

2020-10-31 03:08 UTC, bright-starry-sky commented on src/common/plugin/fulltext/FTStorageAdapter.h
> +    virtual StatusOr<bool> bulk(const HttpClient& client,
> After digging a little in storage, there comes one question: since bulk need to support both put and delete in one batch, so I guess the DocItem need one more parameter to know it is put or delete?
> 
> The process would be `parse wal` -> `decode into kv with operation type` -> `DocItem` -> `http request`?

We don't need to handler about delete data for es. allow es to have redundant data.

2020-10-31 07:11 UTC, bright-starry-sky commented
Ready to review.

2020-10-31 09:59 UTC, critical27 commented on src/common/interface/meta.thrift
> +struct SignInFTServiceReq {
Do we still need these methods?

2020-10-31 10:05 UTC, bright-starry-sky commented on src/common/interface/meta.thrift
> +struct SignInFTServiceReq {
I think so. SignInFTServiceReq used to handle Elasticsearch clients. Listener used to handle `kv` nodes. I think it's better to be independent. WDYT?

2020-11-02 07:04 UTC, darionyaphet commented on src/common/plugin/fulltext/elasticsearch/ESGraphAdapter.cpp
> +    << "_cat/indices/" << index << "?format=json" << "\"";
alignment ?

2020-11-03 01:20 UTC, bright-starry-sky commented on src/common/plugin/fulltext/elasticsearch/ESGraphAdapter.cpp
> +    << "_cat/indices/" << index << "?format=json" << "\"";
> alignment ?

Good point. thanks.

2020-11-07 12:01 UTC, bright-starry-sky commented
integrate with listener.

2020-11-09 06:52 UTC, critical27 commented on src/common/plugin/fulltext/elasticsearch/ESGraphAdapter.cpp
> +    //      -XPUT "http://127.0.0.1:9200/index_exist"
Better rename all `index_exist`, it seems is nebula_spaceName_tag/edge according to https://github.com/vesoft-inc/nebula-graph/pull/365

2020-11-16 03:17 UTC, bright-starry-sky commented
Done. ready to review.

2020-11-16 07:49 UTC, critical27 commented on src/common/plugin/fulltext/FTGraphAdapter.h
> +    virtual StatusOr<bool> prefix(const HttpClient& client,
return Status is enough?

2020-11-16 07:49 UTC, critical27 commented on src/common/interface/meta.thrift
> +struct SignInFTServiceReq {
After a rethink, what do you think of use a `gflag` instead of adding more sing in/out?

2020-11-16 07:49 UTC, critical27 commented on src/common/plugin/fulltext/elasticsearch/ESGraphAdapter.h
> +    StatusOr<bool> prefix(const HttpClient& client,
It seems all these interfaces return `Status` is enough?

2020-11-16 08:25 UTC, bright-starry-sky commented on src/common/plugin/fulltext/FTGraphAdapter.h
> +    virtual StatusOr<bool> prefix(const HttpClient& client,
> return Status is enough?

Emm.. I don't think so. Three types of errors may be returned：

1. Status::ERROR : means http error or FT api error. retry needed if this error occurs.
2. true : Execute successfully
3. false : Elasticsearch internal error, which can be a result set parse error. not need retry.

2020-11-16 08:29 UTC, bright-starry-sky commented on src/common/interface/meta.thrift
> +struct SignInFTServiceReq {
> After a rethink, what do you think of use a `gflag` instead of adding more sing in/out?

Good question. Both way are OK.I just think meta-management is more user friendly. If using gflag, need to add this parameter to both storage and graph, and they must be made available.

2020-11-17 08:29 UTC, critical27 commented on src/common/plugin/fulltext/FTGraphAdapter.h
> +    virtual StatusOr<bool> prefix(const HttpClient& client,
Got it

2020-11-21 02:19 UTC, bright-starry-sky commented
Resolve the conflict

2020-11-23 02:28 UTC, darionyaphet commented on src/common/plugin/fulltext/FTUtils.h
> +    HttpClient(HttpClient&& v) noexcept
explicit ?

2020-11-23 02:29 UTC, darionyaphet commented on src/common/plugin/fulltext/FTUtils.h
> +    DocItem(DocItem&& v) noexcept
ditto

2020-11-23 02:38 UTC, bright-starry-sky commented on src/common/plugin/fulltext/FTUtils.h
> +    HttpClient(HttpClient&& v) noexcept
Good point. fixed.

2020-11-23 02:39 UTC, bright-starry-sky commented
Addressed darionyaphet's comments.

2020-11-23 04:22 UTC, liuyu85cn requested changes

2020-11-23 04:23 UTC, liuyu85cn commented on src/common/clients/meta/MetaClient.cpp
> +         fulltextClientList_ = std::move(serviceClients);
fulltextClientList_.swap(serviceClients) ?

2020-11-23 06:51 UTC, bright-starry-sky commented on src/common/clients/meta/MetaClient.cpp
> +         fulltextClientList_ = std::move(serviceClients);
> fulltextClientList_.swap(serviceClients) ?

What is the advantage? I don't think need to `swap`, `move` is enough.

2020-11-23 07:15 UTC, bright-starry-sky commented on src/common/clients/meta/MetaClient.cpp
> +         fulltextClientList_ = std::move(serviceClients);
> > fulltextClientList_.swap(serviceClients) ?
> 
> What is the advantage? I don't think need to `swap`, `move` is enough.

Your comments led me to other improvements

2020-11-23 07:20 UTC, bright-starry-sky commented
Simplified the method `loadFulltextClients`

2020-11-23 07:32 UTC, liuyu85cn submitted a review, later dismissed

2020-11-23 08:49 UTC, critical27 approved these changes
LGTM

2020-11-23 08:49 UTC, critical27 commented on src/common/meta/Common.h
> +
This could be removed. Previous PR has merged.

2020-11-23 12:44 UTC, panda-sheep reviewed
Good job， Excellent👍

2020-11-23 12:44 UTC, panda-sheep commented on src/common/plugin/fulltext/elasticsearch/ESGraphAdapter.cpp
> +    //      -XDELETE "http://127.0.0.1:9200/index_exist"
Use this interface to delete data in es?

2020-11-23 12:44 UTC, panda-sheep commented on src/common/plugin/fulltext/elasticsearch/ESGraphAdapter.h
> +#ifndef NEBULA_PLUGIN_ESGRAPHADAPTER_H
`COMMON_PLUGIN_ESGRAPHADAPTER_H `   is better？

2020-11-23 12:44 UTC, panda-sheep commented on src/common/plugin/fulltext/FTUtils.h
> +    HostAddr host;
The naming of member variables ends with an underscore
Same as below

2020-11-23 12:44 UTC, panda-sheep commented on src/common/plugin/fulltext/FTUtils.h
> +    std::string val;
ditto

2020-11-23 12:44 UTC, panda-sheep commented on src/common/plugin/fulltext/elasticsearch/ESStorageAdapter.cpp
> +    VLOG(3) << ret;
`VLOG(3) << "Bulk insert failed" << ret;  `   is better?

2020-11-23 12:44 UTC, panda-sheep commented on src/common/plugin/fulltext/test/FulltextPluginTest.cpp
> +    HostAddr localHost_{"127.0.0.1", 9200};
If there is no es server on 127.0.0.1, can this UT pass the test?

2020-11-24 02:32 UTC, bright-starry-sky commented on src/common/plugin/fulltext/elasticsearch/ESGraphAdapter.cpp
> +    //      -XDELETE "http://127.0.0.1:9200/index_exist"
> Use this interface to delete data in es?

No, used drop es index.

2020-11-24 02:33 UTC, bright-starry-sky commented on src/common/plugin/fulltext/elasticsearch/ESGraphAdapter.h
> +#ifndef NEBULA_PLUGIN_ESGRAPHADAPTER_H
> `COMMON_PLUGIN_ESGRAPHADAPTER_H ` is better？

the name space is nebula::plugin, I think the `NEBULA_PLUGIN_ESGRAPHADAPTER_H` is ok.

2020-11-24 02:36 UTC, bright-starry-sky commented on src/common/plugin/fulltext/elasticsearch/ESStorageAdapter.cpp
> +    VLOG(3) << ret;
No, here need a '\n'. because a separate display is required here.

2020-11-24 02:37 UTC, bright-starry-sky commented on src/common/plugin/fulltext/test/FulltextPluginTest.cpp
> +    HostAddr localHost_{"127.0.0.1", 9200};
> If there is no es server on 127.0.0.1, can this UT pass the test?

There's no real call to ES here. please review method `createIndexCmd`

2020-11-24 02:41 UTC, bright-starry-sky commented on src/common/plugin/fulltext/FTUtils.h
> +    HostAddr host;
> The naming of member variables ends with an underscore
> Same as below

It's just a personal habit. I see that struct `Edge` doesn't end with an underscore.

2020-11-24 02:45 UTC, bright-starry-sky commented on src/common/clients/meta/MetaClient.cpp
> +    }
> in line 464，use write lock of `localCacheLock_`， here should use read lock of `localCacheLock_`?

I don't think so. There is only one line of code to return the result set. What's the point of using a lock?

2020-11-24 02:50 UTC, bright-starry-sky commented on src/common/meta/Common.h
> +
> This could be removed. Previous PR has merged.

Good point. What did I say , there's a real merger problem. thanks. removed.

2020-11-24 02:57 UTC, darionyaphet commented on src/common/expression/TextSearchExpression.cpp
> +            buf = "FUZZY(";
`Regexp` ?

2020-11-24 03:02 UTC, bright-starry-sky commented on src/common/expression/TextSearchExpression.cpp
> +            buf = "FUZZY(";
Good point. fixed. thanks.

2020-11-24 03:24 UTC, panda-sheep commented on src/common/plugin/fulltext/elasticsearch/ESGraphAdapter.h
> +#ifndef NEBULA_PLUGIN_ESGRAPHADAPTER_H
Because the common code of the common repo is moved to the common directory, it is changed to COMMON_XX, please refer to other files

2020-11-24 03:24 UTC, panda-sheep commented on src/common/clients/meta/MetaClient.cpp
> +    }
My mistake, you are right

2020-11-24 03:25 UTC, panda-sheep commented on src/common/plugin/fulltext/test/FulltextPluginTest.cpp
> +    HostAddr localHost_{"127.0.0.1", 9200};
Got， thx

2020-11-24 06:30 UTC, liuyu85cn approved these changes

2020-11-24 06:39 UTC, critical27 approved these changes
Good job

2020-11-24 06:39 UTC, merged