Add range function
vesoft-inc/nebula-common pull request #314
Opened 2020-11-19 09:30 UTC by czpmango

- add `range` function expression
- add unittest for new expression

2020-11-19 09:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vesoft-inc/nebula-common?pullRequest=314) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vesoft-inc/nebula-common?pullRequest=314) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vesoft-inc/nebula-common?pullRequest=314) it.</sub>

2020-11-19 09:43 UTC, jievince requested changes

2020-11-19 09:43 UTC, jievince commented on src/common/function/FunctionManager.cpp
> +                    res.emplace_back(i);
Does it work for test case such as [1, 5, -2], [1, 5, 0], [5, 1, 2]?

2020-11-19 09:43 UTC, jievince commented on src/common/function/FunctionManager.cpp
> +                    return Status::Error("Incorrect parameter type.");
return Value::kNullBadType;

2020-11-19 09:43 UTC, jievince commented on src/common/function/FunctionManager.cpp
> +            auto range=[](const Value& start, const Value& end, const Value& step = 1) -> StatusOr<Value>{
(const auto &args)

2020-11-19 09:43 UTC, jievince commented on src/common/function/FunctionManager.cpp
> +    }
Check args at  the beginning

2020-11-20 01:30 UTC, czpmango commented on src/common/function/FunctionManager.cpp
> +                    res.emplace_back(i);
Already fixed.

2020-11-20 09:49 UTC, jievince commented on src/common/function/FunctionManager.cpp
> +            }
Don't need to check args'size in attr.body_ because getInternal(func, arity) has check it

2020-11-20 09:49 UTC, jievince commented on src/common/function/FunctionManager.cpp
> +                return Value::kNullBadData;
return Value::kNullBadType;

2020-11-20 09:49 UTC, jievince commented on src/common/function/FunctionManager.cpp
> +                    return Value::kNullBadData;
return Value::kNullBadType;

2020-11-20 09:49 UTC, jievince commented on src/common/function/FunctionManager.cpp
> +            for(auto i = start; step > 0 && i < end; i = i + step){
Have you checked test cases such as range(5, 1, -1)? It's also legal.

2020-11-24 02:56 UTC, czpmango commented on src/common/function/FunctionManager.cpp
> +            }
got it.

2020-11-24 02:57 UTC, czpmango commented on src/common/function/FunctionManager.cpp
> +            for(auto i = start; step > 0 && i < end; i = i + step){
Already fixed.

2020-11-24 03:06 UTC, jievince commented on src/common/function/FunctionManager.cpp
> +            for(auto i = start; step>0?i<end:i>end; i = i + step){
Many programing language's range function doesn't include the `end`, but cypher include it, so whether to include `end` may need a discussion

2020-11-24 03:06 UTC, jievince commented on src/common/function/test/FunctionManagerTest.cpp
> +    }
lack of return type test

2020-11-24 03:06 UTC, jievince commented on src/common/function/FunctionManager.cpp
> +                return Value(List());
cypher reports error when step is 0

2020-11-24 03:08 UTC, CPWstatic commented on src/common/function/FunctionManager.cpp
> +            for(auto i = start; step>0?i<end:i>end; i = i + step){
`step>0?i<end:i>end;`  Need whitespace.

2020-11-24 03:39 UTC, czpmango commented on src/common/function/FunctionManager.cpp
> +            for(auto i = start; step>0?i<end:i>end; i = i + step){
The range behavior has been changed to be consistent with cypher.

2020-11-24 03:41 UTC, czpmango commented on src/common/function/FunctionManager.cpp
> +            for(auto i = start; step>0?i<end:i>end; i = i + step){
Got it.

2020-11-24 04:28 UTC, dutor approved these changes
LGTM.

2020-11-24 06:38 UTC, jievince approved these changes

2020-11-24 07:11 UTC, CPWstatic approved these changes

2020-11-24 07:39 UTC, merged