Fix TypeCastExpression
vesoft-inc/nebula-common pull request #412
Opened 2021-02-08 03:15 UTC by czpmango

Fixes TypeCastExpression behavior to be consistent with OpenCypher.

2021-02-08 03:21 UTC, yixinglu commented on src/common/datatypes/Value.cpp
> +            if (toString().compare("false") == 0) {
you'd better to assign the result of `toString()` to a variable for avoiding this function to be called multiple times.

2021-02-08 03:54 UTC, czpmango commented on src/common/datatypes/Value.cpp
> +            if (toString().compare("false") == 0) {
Fixed, thx.

2021-02-08 06:55 UTC, jievince commented on src/common/datatypes/Value.cpp
> +            std::transform(str.begin(), str.end(), str.begin(), ::tolower);
why not directly call std::lower(toString())?

2021-02-08 07:28 UTC, czpmango commented on src/common/datatypes/Value.cpp
> +            std::transform(str.begin(), str.end(), str.begin(), ::tolower);
std::tolower?

2021-02-08 07:29 UTC, jievince commented on src/common/datatypes/Value.cpp
> +            std::transform(str.begin(), str.end(), str.begin(), ::tolower);
I'am sorry. Seems std::string doesn't has tolower()

2021-02-08 08:28 UTC, panda-sheep commented on src/common/datatypes/Value.cpp
> +Value Value::toBool() {
please convert to bool in this function

2021-02-08 08:35 UTC, panda-sheep requested changes
please convert Value::toBool  to bool

2021-02-08 08:54 UTC, czpmango commented on src/common/datatypes/Value.cpp
> +Value Value::toBool() {
You could get the bool type return value explicitly in the caller interface.

2021-02-08 08:57 UTC, panda-sheep commented on src/common/datatypes/Value.cpp
> +Value Value::toBool() {
I don’t think so, I think you should check the original function implementation

2021-02-23 07:29 UTC, critical27 commented
> - 字符串 "true"/"FaLse" 等会返回转换后的 bool 值

Why do you prefer literally true/false to empty?

2021-03-01 06:06 UTC, czpmango commented
> > * 字符串 "true"/"FaLse" 等会返回转换后的 bool 值
> 
> Why do you prefer literally true/false to empty?

Consistent with the openCypher standard.

neo4j test:
```
neo4j@neo4j> return toBoolean("FaLse");
+--------------------+
| toBoolean("FaLse") |
+--------------------+
| FALSE              |
+--------------------+
```

2021-03-03 02:41 UTC, panda-sheep submitted a review, later dismissed
Good job，lgtm

2021-03-03 03:01 UTC, panda-sheep approved these changes

2021-03-03 08:59 UTC, panda-sheep approved these changes

2021-03-04 07:34 UTC, yixinglu approved these changes

2021-03-05 02:43 UTC, merged